baseURL: "https://hdl.github.io/awesome"
title: "Awesome resources for Hardware Description"
theme: "bare-hugo-theme"
enableGitInfo: true

params:
  shorttitle: "Awesome HDL"
  description: 'Tools, frameworks, IP cores, libraries and more!'
  # PostCSS is harder than it should be to get working on a theme
  # example site. It's easy on _your_ site.
  postcss: false
  social:
    - icon: "github"
      url: "https://github.com/hdl/awesome"
  categories:
    "Boards": ""
    "Conferences": ""
    "Cores": ""
    "Cores:Collection": "Groups of individual IP cores"
    "Cores:Library": "Strong-related set of IP cores"
    "Cores:Single": "Single IP cores"
    "Frameworks": ""
    "Frameworks:Verification": "Frameworks for verification"
    "Languages": ""
    "Resources": ""
    "Resources:Books": "Books"
    "Resources:Social Media": "Social Media Network pages"
    "Resources:Websites": "Websites"
    "Resources:Weekly": "Weekly publications"
    "Resources:Wiki": "Wikis"
    "Services": ""
    "Services:Code Quality": "Code Quality services"
    "Services:Continuous Documentation": "Continuous Documentation services"
    "Services:Continuous Integration": "Continuous Integration services"
    "Tools": ""
    "Tools:Bitgen": "Bitstream generation programs"
    "Tools:Grammars": "Grammars"
    "Tools:Managers": ""
    "Tools:Package Managers": ""
    "Tools:Parsers": ""
    "Tools:PnRs": "Place and Route programs"
    "Tools:Programmers": "Programmers"
    "Tools:Simulators": "Simulators"
    "Tools:Synthesizers": "Synthesizers"
    "Tools:Verification": "Verification"
    "Tools:Waveform Viewer": "Waveform viewers"
    "Verification": ""
    "Verification:Models": "Single verification models"
    "Verification:Models:Interface": "Verification model for Interfaces"
    "Verification:Models:Memory": "Verification model for Memories"

menu:
  main:
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 1
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3
